name: github_todo
version: 0.0.2
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.

environment:
  sdk: '2.0.0-dev.67.0'

dependencies:
  sass_builder: ^2.0.0
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: '>=0.3.6 <0.5.0'
  ctrl_alt_foo2: any
  googleapis: any
  googleapis_auth: any
  intl: any
  sass: ^1.9.0
