name: github_todo
version: 0.0.2
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.

environment:
  sdk: '2.7.1'

dependencies:
  sass_builder: ^2.0.0
  build_runner: '>=1.6.2 <2.0.0'
  build_test: ^0.10.2
  build_web_compilers: '>=1.2.0 <3.0.0'
  ctrl_alt_foo2:
    git: git@github.com:dddaisuke/ctrl-alt-foo.git
  googleapis: any
  googleapis_auth: any
  intl: any
  sass: ^1.9.0
